name: atlas-data
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=4
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - asttokens=2.0.5
  - attrs=24.3.0
  - awkward=2.7.4
  - awkward-cpp=44
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.3.1
  - cramjam=2.8.4rc3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - fontconfig=2.14.2
  - fonttools=4.55.3
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2025.3.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pyzmq=26.2.0
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uproot=5.5.2
  - urllib3=2.3.0
  - vector=1.6.1
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xxhash=0.8.3
  - xz=5.6.4
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
