# KEDA RabbitMQ-Secret YAML
apiVersion: v1
kind: Secret
metadata:
  name: keda-secret
  namespace: default
data:
  # Base64 - amqp://rabbitmq.default.svc.cluster.local:5672/
  host: YW1xcDovL3JhYmJpdG1xLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi8=
  # Base64 - guest
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=