# BusyBox-Higgs-Plot YAML
apiVersion: v1
kind: Pod
metadata:
  name: busybox-higgs-plot
spec:
  containers:
  - name: busybox-higgs-plot
    image: busybox
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
    - name: higgs-volume
      mountPath: /output
  volumes:
  - name: higgs-volume
    persistentVolumeClaim:
      claimName: higgs-volume-claim