# Higgs-Manager YAML
apiVersion: batch/v1
kind: Job
metadata:
  name: manager
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: manager
        image: higgs-manager:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: higgs-volume
          mountPath: /app/output
      volumes:
      - name: higgs-volume
        persistentVolumeClaim:
          claimName: higgs-volume-claim
